### ISSUE TITLE
where is the time_steps，iterations and music，they don't be define in this function

### ISSUE THREAD

**Issue by BLACKMogus** [dshieble/Music_RNN_RBM#16]
I used

 music = tf.concat([music, x_out],0)

And

 loop_vars = [time_steps, iterations, U, u_t, x, music]
        [_, _, _, _, _, music] = tf.while_loop(lambda count, num_iter, *args: count < num_iter, generate_recurrence,
                                           loop_vars, shape_invariants=[time_steps.get_shape(), iterations.get_shape(),
                                                             U.get_shape(), u_t.get_shape(),x.get_shape(), tf.TensorShape([None, None])])

_Originally posted by @Guije2018 in https://github.com/dshieble/Music_RNN_RBM/issues/12#issuecomment-443464099_

**Comment by KartikayKaul** [comment]
Edited : `time_steps` seems to be same as using `num`. (The argument of the function)
Although I can't figure out what should be replacing the `iterations` variable.
